-- 코드를 입력하세요

SELECT TITLE, USED_GOODS_BOARD.BOARD_ID, REPLY_ID, USED_GOODS_REPLY.WRITER_ID, USED_GOODS_REPLY.CONTENTS, USED_GOODS_REPLY.CREATED_DATE FROM USED_GOODS_BOARD INNER JOIN USED_GOODS_REPLY ON USED_GOODS_BOARD.BOARD_ID = USED_GOODS_REPLY.BOARD_ID WHERE DATE_FORMAT(USED_GOODS_BOARD.CREATED_DATE, '%Y-%m') = '2022-10' ORDER BY USED_GOODS_REPLY.CREATED_DATE ASC, TITLE ASC;